{"uuid": "c7b68f00-b3cb-428b-bc05-00955574a048", "counter": 53, "stdout": "\u001b[0;31mfatal: [demo03]: FAILED! => {\"changed\": false, \"msg\": \"Unable to start service vsftpd: Job for vsftpd.service failed because the control process exited with error code.\\nSee \\\"systemctl status vsftpd.service\\\" and \\\"journalctl -xeu vsftpd.service\\\" for details.\\n\"}\u001b[0m\r\n\u001b[0;36m...ignoring\u001b[0m", "start_line": 71, "end_line": 73, "runner_ident": "1e2c383b-91d3-4821-b8f8-74876d20e6d9", "event": "runner_on_failed", "pid": 161495, "created": "2025-05-15T17:46:21.503121+00:00", "parent_uuid": "005056b7-f67d-7431-0aa6-000000000012", "event_data": {"playbook": "/tmp/tmpmbv02kxg.yml", "playbook_uuid": "191d3bba-4448-4da1-8c30-5f59100ead4d", "play": "Soluci\u00f3n final para VSFTPD", "play_uuid": "005056b7-f67d-7431-0aa6-000000000002", "play_pattern": "demo03", "task": "Reiniciar VSFTPD", "task_uuid": "005056b7-f67d-7431-0aa6-000000000012", "task_action": "service", "resolved_action": "ansible.builtin.service", "task_args": "", "task_path": "/tmp/tmpmbv02kxg.yml:169", "host": "demo03", "remote_addr": "demo03", "res": {"msg": "Unable to start service vsftpd: Job for vsftpd.service failed because the control process exited with error code.\nSee \"systemctl status vsftpd.service\" and \"journalctl -xeu vsftpd.service\" for details.\n", "invocation": {"module_args": {"name": "vsftpd", "state": "restarted", "enabled": true, "daemon_reload": false, "daemon_reexec": false, "scope": "system", "no_block": false, "force": null, "masked": null}}, "_ansible_no_log": false, "changed": false}, "start": "2025-05-15T17:46:17.493128+00:00", "end": "2025-05-15T17:46:21.502713+00:00", "duration": 4.009585, "ignore_errors": true, "event_loop": null, "uuid": "c7b68f00-b3cb-428b-bc05-00955574a048"}}