{"uuid": "46a5d0bb-4044-4dcb-86a6-91d4ad0dff4e", "counter": 53, "stdout": "\u001b[0;31mfatal: [demo03]: FAILED! => {\"changed\": false, \"msg\": \"Unable to start service vsftpd: Job for vsftpd.service failed because the control process exited with error code.\\nSee \\\"systemctl status vsftpd.service\\\" and \\\"journalctl -xeu vsftpd.service\\\" for details.\\n\"}\u001b[0m\r\n\u001b[0;36m...ignoring\u001b[0m", "start_line": 71, "end_line": 73, "runner_ident": "0b62395c-94e9-4d1a-9dc1-38219280428c", "event": "runner_on_failed", "pid": 164457, "created": "2025-05-15T18:10:30.102936+00:00", "parent_uuid": "005056b7-f67d-b869-4380-000000000012", "event_data": {"playbook": "/tmp/tmp6q271tnb.yml", "playbook_uuid": "29585e9f-fae0-458d-ba3d-3d8bef5a0180", "play": "Soluci\u00f3n final para VSFTPD", "play_uuid": "005056b7-f67d-b869-4380-000000000002", "play_pattern": "demo03", "task": "Reiniciar VSFTPD", "task_uuid": "005056b7-f67d-b869-4380-000000000012", "task_action": "service", "resolved_action": "ansible.builtin.service", "task_args": "", "task_path": "/tmp/tmp6q271tnb.yml:169", "host": "demo03", "remote_addr": "demo03", "res": {"msg": "Unable to start service vsftpd: Job for vsftpd.service failed because the control process exited with error code.\nSee \"systemctl status vsftpd.service\" and \"journalctl -xeu vsftpd.service\" for details.\n", "invocation": {"module_args": {"name": "vsftpd", "state": "restarted", "enabled": true, "daemon_reload": false, "daemon_reexec": false, "scope": "system", "no_block": false, "force": null, "masked": null}}, "_ansible_no_log": false, "changed": false}, "start": "2025-05-15T18:10:26.085237+00:00", "end": "2025-05-15T18:10:30.102525+00:00", "duration": 4.017288, "ignore_errors": true, "event_loop": null, "uuid": "46a5d0bb-4044-4dcb-86a6-91d4ad0dff4e"}}