{"uuid": "8a686385-d782-4301-821c-e7866660477e", "counter": 5, "stdout": "\u001b[0;31mfatal: [demo01]: FAILED! => {\"changed\": false, \"module_stderr\": \"/bin/sh: line 1: /usr/bin/python3.12: No such file or directory\\n\", \"module_stdout\": \"\", \"msg\": \"The module failed to execute correctly, you probably need to set the interpreter.\\nSee stdout/stderr for the exact error\", \"rc\": 127}\u001b[0m", "start_line": 4, "end_line": 5, "runner_ident": "6fa0d654-642f-4777-a927-f4253298e050", "event": "runner_on_failed", "pid": 41594, "created": "2025-05-08T02:18:26.803826+00:00", "parent_uuid": "005056b7-f67d-0bb2-a95e-000000000004", "event_data": {"playbook": "/opt/www/media/yml/ping_FvQN7aI.yml", "playbook_uuid": "5df787fa-94ec-4e08-8ca6-05c3b6bb13c8", "play": "Verificar conectividad con un host remoto", "play_uuid": "005056b7-f67d-0bb2-a95e-000000000002", "play_pattern": "target_host", "task": "Hacer ping al host remoto", "task_uuid": "005056b7-f67d-0bb2-a95e-000000000004", "task_action": "ansible.builtin.ping", "resolved_action": "ansible.builtin.ping", "task_args": "", "task_path": "/opt/www/media/yml/ping_FvQN7aI.yml:7", "host": "demo01", "remote_addr": "demo01", "res": {"module_stdout": "", "module_stderr": "/bin/sh: line 1: /usr/bin/python3.12: No such file or directory\n", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127, "_ansible_no_log": false, "changed": false}, "start": "2025-05-08T02:18:26.519948+00:00", "end": "2025-05-08T02:18:26.803521+00:00", "duration": 0.283573, "ignore_errors": null, "event_loop": null, "uuid": "8a686385-d782-4301-821c-e7866660477e"}}