{"uuid": "54784c5d-85fb-45f4-8b3e-b95c8cb74730", "counter": 53, "stdout": "\u001b[0;31mfatal: [demo02]: FAILED! => {\"changed\": false, \"msg\": \"One or more supplied key could not be found in the database.\"}\u001b[0m\r\n\u001b[0;36m...ignoring\u001b[0m", "start_line": 57, "end_line": 59, "runner_ident": "c28c2bed-8661-4d2c-82c1-435160677aaf", "event": "runner_on_failed", "pid": 257686, "created": "2025-05-16T20:03:33.356492+00:00", "parent_uuid": "005056b7-f67d-deec-ca13-000000000014", "event_data": {"playbook": "/tmp/tmpvrww5h99.yml", "playbook_uuid": "913b213a-1643-42d7-a743-9c7497e734f1", "play": "Instalaci\u00f3n y configuraci\u00f3n de Pure-FTPd para hosts", "play_uuid": "005056b7-f67d-deec-ca13-000000000002", "play_pattern": "demo02", "task": "Verificar si el usuario FTP existe", "task_uuid": "005056b7-f67d-deec-ca13-000000000014", "task_action": "getent", "resolved_action": "ansible.builtin.getent", "task_args": "", "task_path": "/tmp/tmpvrww5h99.yml:149", "host": "demo02", "remote_addr": "demo02", "res": {"msg": "One or more supplied key could not be found in the database.", "invocation": {"module_args": {"database": "passwd", "key": "ftpuser", "fail_key": true, "service": null, "split": null}}, "_ansible_no_log": false, "changed": false}, "start": "2025-05-16T20:03:32.541433+00:00", "end": "2025-05-16T20:03:33.356128+00:00", "duration": 0.814695, "ignore_errors": true, "event_loop": null, "uuid": "54784c5d-85fb-45f4-8b3e-b95c8cb74730"}}