{"uuid": "b6875e22-68fa-4adf-b89e-48b0808b9bc5", "counter": 37, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option\u001b[0m\r\n\u001b[0;31mfatal: [demo03]: FAILED! => {\"changed\": false, \"msg\": \"Could not find or access '/opt/www/media/templates/virtualhost.conf.j2' on the Ansible Controller.\\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\"}\u001b[0m", "start_line": 34, "end_line": 36, "runner_ident": "67a8c1d6-8ef5-4075-9cbd-996f81ccc656", "event": "runner_on_failed", "pid": 103363, "created": "2025-05-17T01:11:15.429312+00:00", "parent_uuid": "005056b7-f67d-7ac9-2752-000000000010", "event_data": {"playbook": "/tmp/tmpo57dcq_y.yml", "playbook_uuid": "3f6e922f-90b8-4102-b634-6f7806b8c19a", "play": "Configuraci\u00f3n completa de servidor web con HTTPS", "play_uuid": "005056b7-f67d-7ac9-2752-000000000002", "play_pattern": "demo03", "task": "Configurar VirtualHost HTTP", "task_uuid": "005056b7-f67d-7ac9-2752-000000000010", "task_action": "template", "resolved_action": "ansible.builtin.template", "task_args": "", "task_path": "/tmp/tmpo57dcq_y.yml:73", "host": "demo03", "remote_addr": "demo03", "res": {"msg": "Could not find or access '/opt/www/media/templates/virtualhost.conf.j2' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option", "exception": "Traceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/ansible/plugins/action/template.py\", line 85, in run\n    source = self._find_needle('templates', source)\n  File \"/usr/lib/python3.9/site-packages/ansible/plugins/action/__init__.py\", line 1431, in _find_needle\n    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)\n  File \"/usr/lib/python3.9/site-packages/ansible/parsing/dataloader.py\", line 341, in path_dwim_relative_stack\n    raise AnsibleFileNotFound(file_name=source, paths=[to_native(p) for p in search])\nansible.errors.AnsibleFileNotFound: Could not find or access '/opt/www/media/templates/virtualhost.conf.j2' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\n", "_ansible_no_log": false, "changed": false}, "start": "2025-05-17T01:11:15.145525+00:00", "end": "2025-05-17T01:11:15.428879+00:00", "duration": 0.283354, "ignore_errors": null, "event_loop": null, "uuid": "b6875e22-68fa-4adf-b89e-48b0808b9bc5"}}